import { LegalPage } from '../../components/legal-page';

export default function PrivacyPage() {
  return <LegalPage eyebrow="Privacy policy" title="A straightforward approach to your information." intro="This policy explains what Norivex Cyber collects through assessment requests, why it is needed, and how it is handled when you choose to get in touch." sections={[
    { heading: 'Information collected through the assessment request form', paragraphs: ['When you submit an assessment request, the form may collect the following information:'], bullets: ['Name', 'Business name', 'Email', 'Optional phone number', 'Website or domain', 'Industry', 'Company size', 'Requested areas of review', 'Preferred contact method', 'Additional information you voluntarily submit'] },
    { heading: 'Why this information is collected', paragraphs: ['The information is used only to review your request, communicate with you, determine an appropriate scope, and provide related service communications. It helps Norivex Cyber understand what you would like reviewed before any conversation or assessment is planned.'] },
    { heading: 'Email processing and service providers', paragraphs: ['Assessment request details are sent through email processing and delivery providers such as Resend so that Norivex Cyber can receive and respond to the request. Those providers may process the information needed to deliver the message according to their own terms and privacy practices.'] },
    { heading: 'Basic logs and security', paragraphs: ['The website or its hosting platform may create basic server and security logs, such as request timing, route information, or technical details needed to keep the service reliable and protect it from abuse. Norivex Cyber does not intentionally use these logs to build marketing profiles.'] },
    { heading: 'Retention and sharing', paragraphs: ['Submitted information is kept for a reasonable period needed to review the request, communicate with the requester, and maintain related service records. Norivex Cyber does not sell submitted personal information. Information may be shared with service providers involved in operating the website or delivering request notifications, as described above.'] },
    { heading: 'Correction or deletion requests', paragraphs: ['To request a correction or deletion of information you submitted, contact Connor at hello@norivexcyber.com. Include enough context to help identify the request. Norivex Cyber will review the request and respond as reasonably possible, subject to information that must be retained for security, legal, or operational reasons.'] },
    { heading: 'Contact information', paragraphs: ['Questions about this policy or an assessment request can be sent to hello@norivexcyber.com or by phone at 276-806-0921.'] },
  ]} />;
}
